name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  build-and-publish:
    uses: yeencloud/dpl-ci/.github/workflows/issue.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}