name: Test and publish service

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  bump-version:
    uses: yeencloud/dpl-ci/.github/workflows/bump-version.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # we don't want this job to trigger a new pipeline run

  build-and-publish:
    needs: bump-version
    uses: yeencloud/dpl-ci/.github/workflows/package.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  create-release:
    needs: build-and-publish
    uses: yeencloud/dpl-ci/.github/workflows/create-release.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
